### ISSUE TITLE
Question : ScroolViewHeigh

### ISSUE THREAD

**Issue by ZebedeeTR** [BTLibrary/BTGlassScrollView#11]
Hi. Thank you so much for this control.

I have a question.

My foregroundView's heigh is variable. Sometime is 500 px, sometimes 900 px.
How do I set the scroll?
Sometimes it does not fit on the screen.
That my code below. What's wrong?

``` objectivec
    MyVC * content = [[UIStoryboard storyboardWithName:@"Main" bundle:nil] instantiateViewControllerWithIdentifier:@"MyVC"];
    content.view.backgroundColor =[UIColor clearColor];
    content.view.opaque = NO;
    [content prepareUI:self];
    CGRect aFrame = CGRectMake(0, 0, content.view.frame.size.width, content.view.frame.size.height);

    UIImage * aImage = [Genel getImage:[aMy.id stringValue]];

    _glassScrollView = [[BTGlassScrollView alloc] initWithFrame:aFrame BackgroundImage:aImage blurredImage:nil viewDistanceFromBottom:120 foregroundView:content.view];

//    aFrame = _glassScrollView.frame;
#warning THE FOLLOWING LINE SETS THE FRAME HEIGHT.
//    aFrame.size.height = [content frameHeight];
//    _glassScrollView.frame = aFrame;

    [self.view addSubview:_glassScrollView];
```

**Comment by ace1294** [comment]
I'm wondering the same thing, have you had any luck solving this issue?

**Comment by ZebedeeTR** [comment]
Yes. I set the frame height on this function. It works fine.
- (void)viewWillLayoutSubviews 
  {
  CGRect aFrame = _glassScrollView.foregroundView.frame;
  aFrame.size.height = _contentHeigth;
  _glassScrollView.foregroundView.frame = aFrame;
  
  [_glassScrollView setTopLayoutGuideLength:[self.topLayoutGuide length]];
  }
