### ISSUE TITLE
License

### ISSUE THREAD

**Issue by georgemp** [BTLibrary/BTGlassScrollView#3]
Hi, 
  This seems to be a nice UI control. Could you update the repository with a LICENSE file, so that it is clear how you intend for the code to be re-used? I believe you mean to allow re-use by your README, but, just wanted to be sure. Thanks

georgemp

**Comment by BTLibrary** [comment]
Hello georgemp! 

I just have a couple of seconds at the moment, so quick answer is, do as you please with it. You may claim it as your own or credit me, either way, the code get used and that is what is important :). I think Apache 2.0 has that kind of license but I am not sure. I will research on it and update the repository as soon as I get time (next year at least).

Thank you for the interest and if you have any comment please feel free, I always welcome others opinion.
Merry Christmas,
Byte

**Comment by georgemp** [comment]
Thanks...and a Merry Christmas to you too.

**Comment by BTLibrary** [comment]
I just added a clause into the Read me. As far as I know, it is suffice for the time being. Cheers!
